### ISSUE TITLE
Fails if optional argument of (is..) is nil 

### ISSUE THREAD

**Issue by mmmdreg** [lambdaisland/kaocha#76] opened 2019-02-28 14:19 UTC
Apologies if I miss details as I am typing from a phone as I cannot access github from work. 

Using clojure.test and trying  out kaocha for the first time. 

The ‘is’ function takes an optional 2nd argument to document the test. Whether it is idiomatic or not, I have a few clojure.spec based tests that look like (is (s/valid?...) (s/explain-str...)), which will print out a useful error message if a validation fails and nil otherwise. 

This works with ‘lein test’ and the ‘run-tests’ function in the REPL, but kaocha throws its own spec error and fails. 

The expected behavior would be to not fail. 

I think you can reproduce this just by passing a nil second argument directly. 

Thanks for your work!

**Comment by alysbrooks** [comment] 2020-12-02 23:36
I'm not able to reproduce this. I'm not sure if we've fixed this since or the reproducible case is narrower than just any `is` that has a nil second argument.

**Comment by plexus** [comment] 2020-12-10 15:38
This may depend on the reporter used, not sure. If someone still runs into this issue please create a repo that reproduces it, should be easy to fix once we know what's going on. I'm going to close this issue for now.

**Closed by plexus** 2020-12-10 15:38 UTC
