### ISSUE TITLE
Improvement: Output stacktrace if test file can't be compiled?

### ISSUE THREAD

**Issue by leppaott** [lambdaisland/kaocha#221] opened 2021-04-27 07:08 UTC
May be due how kaocha loads test files but one thing I still need to use lein test from time to time. If the test file can't be compiled kaocha ouputs not very helpful:
`WARNING: No tests were found, make sure :test-paths and :ns-patterns are configured correctly in tests.edn.`

Whereas lein test helps me find the error:
`Exception in thread "main" Syntax error reading source at (...).
        at clojure.lang.Compiler.load(Compiler.java:7642)
....Caused by: java.lang.RuntimeException: Unsupported escape character:...`

**Comment by plexus** [comment] 2021-04-27 07:12
Duplicate of https://github.com/lambdaisland/kaocha/issues/208 , please join the discussion there.

**Comment by alysbrooks** [comment] 2021-05-07 15:46
Since this is a duplicate, I'm closing the issue. Feel free to reopen or comment if you disagree, @leppaott.

**Closed by alysbrooks** 2021-05-07 15:46 UTC
