### ISSUE TITLE
No tests found should fail?

### ISSUE THREAD

**Issue by AndreaCrotti** [lambdaisland/kaocha#229] opened 2021-06-25 10:29 UTC
I was fooled a few times into thinking that my test suite was all green, when in fact simply no tests were discovered.
This is particularly annoying maybe when you use other reporters that don't give you the report at the end.

I wonder why Kaocha should not just fail when it can't actually find anything to run, any reason why it could not just fail in that case?

**Comment by alysbrooks** [comment] 2021-06-25 15:37
Yes, this should at least be something users can opt in to. A lot of people expect this behavior, so I wonder if it should really be the new default, but changing it is arguably a breaking change, which we want to avoid at all costs.

This is a duplicate of #211

**Comment by plexus** [comment] 2021-09-16 08:12
Closing as this is a duplicate.

**Closed by plexus** 2021-09-16 08:12 UTC
